apiVersion: v1
kind: ReplicationController
metadata:
  name: mssql-operator-rc
spec:
  replicas: 1
  selector:
    app: mssql-operator
  template:
    metadata:
      labels:
        app: mssql-operator
    spec:
      containers:
      - name: mssql-operator
        image: synax/mssql-operator:latest
        ports:
        - containerPort: 8080
          protocol: TCP
---
kind: Service
apiVersion: v1
metadata:
  name: mssql-operator-svc
spec:
  selector:
    app: mssql-operator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080